
server:
  port: 9001
logging:
#  file:
#    path: /tmp/user-service/logs
  level:
    org: DEBUG
#    org.springframework.context: DEBUG
spring:
  application:
    name: user-service
eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
debug: true
